"""Fernet-based encryption for application secrets stored in the DB.

Only values that must be later decrypted (the Entra client_secret is
the paradigmatic case) use this module. Values that only need to be
compared — SMTP passwords and the UI admin password — are bcrypt-hashed,
never encrypted, and are handled elsewhere.

The key is read from the ENCRYPTION_KEY environment variable. It is
never written to disk, never logged, and never returned by any API.
Losing the key means losing access to every encrypted row; rotating it
requires re-entering every encrypted secret through the UI.
"""

from __future__ import annotations

import base64
import os
from functools import lru_cache

from cryptography.fernet import Fernet, InvalidToken


class CryptoError(RuntimeError):
    """Raised when encryption or decryption fails."""


@lru_cache(maxsize=1)
def _get_fernet() -> Fernet:
    """Build the Fernet instance once per process.

    Validates the key shape early so a misconfigured container fails fast
    at startup rather than at the first secret write.
    """
    raw = os.environ.get("ENCRYPTION_KEY", "").strip()
    if not raw:
        raise CryptoError(
            "ENCRYPTION_KEY is not set. Generate one with "
            "`python -c \"from cryptography.fernet import Fernet; "
            "print(Fernet.generate_key().decode())\"` and set it in the "
            "container environment."
        )
    # Fernet keys are 32 URL-safe-base64-encoded bytes (44 chars with padding).
    try:
        decoded = base64.urlsafe_b64decode(raw.encode("ascii"))
    except Exception as exc:
        raise CryptoError(
            "ENCRYPTION_KEY is not valid URL-safe base64."
        ) from exc
    if len(decoded) != 32:
        raise CryptoError(
            "ENCRYPTION_KEY must decode to exactly 32 bytes (generated by "
            "Fernet.generate_key())."
        )
    return Fernet(raw.encode("ascii"))


def encrypt_str(plaintext: str) -> str:
    """Encrypt a UTF-8 string, returning the Fernet token as a str."""
    if plaintext is None:
        raise CryptoError("Cannot encrypt None.")
    token = _get_fernet().encrypt(plaintext.encode("utf-8"))
    return token.decode("ascii")


def decrypt_str(token: str) -> str:
    """Decrypt a Fernet token produced by encrypt_str."""
    if not token:
        raise CryptoError("Cannot decrypt an empty token.")
    try:
        raw = _get_fernet().decrypt(token.encode("ascii"))
    except InvalidToken as exc:
        # Do NOT include the token or any partial data in the exception
        # message — it would end up in logs.
        raise CryptoError(
            "Decryption failed: token invalid or ENCRYPTION_KEY changed."
        ) from exc
    return raw.decode("utf-8")
